version: "3"
services:
  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    container_name: "test-postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: