spring:
  main:
    banner-mode: 'off'
  application:
    name: '@project.name@'
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 1234
    initialize: false
  batch:
    jdbc:
      initialize-schema: always

thread-count: 5

endpoint:
  name: mockarooendpoint
  url: https://my.api.mockaroo.com

target:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: fosql

source-table: person_source
target-table: person_target
final-target-table: person_final_target
file-save-location: /tmp/Persons/

ftp:
  hostname: localhost
  port: 9021
  username: balazs
  password: 1234
  file-path: ftp.txt

logging:
  config: src/main/resources/logback-spring.xml
  level:
    root: INFO

log:
  dir: /tmp/Persons