spring:
  main:
    banner-mode: 'off'
  application:
    name: '@project.name@'
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: test
    password: test
  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    root: INFO