spring:
  main:
    banner-mode: 'off'
  application:
    name: '@project.name@'
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 1234
  batch:
    jdbc:
      initialize-schema: always

source-table: person_source
target-table: person_target
file-save-location: /tmp/Persons/

logging:
  level:
    root: DEBUG