spring:
  main:
    banner-mode: 'off'
  application:
    name: '@project.name@'
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: fosql
  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    root: INFO